import React from 'react';
import { 
  Truck, 
  ShieldCheck, 
  MapPin, 
  Clock, 
  Package, 
  Zap, 
  BarChart3, 
  CheckCircle2, 
  Headphones, 
  ArrowRight,
  Sparkles,
  HelpCircle,
  ChevronDown
} from 'lucide-react';

export const LandingFeatures: React.FC = () => {
  const [openFaq, setOpenFaq] = React.useState<number | null>(null);

  const faqs = [
    {
      q: "Where can I find my AWB / Tracking ID?",
      a: "Your AWB (Air Waybill) tracking number is provided in your order confirmation SMS, email, or invoice generated by the seller/admin when your shipment is created."
    },
    {
      q: "How does real-time tracking update work?",
      a: "As your package moves between Amazon Fulfillment Centers, Sorting Hubs, and Air Terminals, delivery agents scan the barcode at each checkpoint, updating your tracking status live in our database."
    },
    {
      q: "What does 'Out for Delivery' status mean?",
      a: "Out for delivery means your package has arrived at your local delivery station and has been assigned to a delivery associate who is on the route to deliver your package today."
    },
    {
      q: "How do I verify a COD (Cash on Delivery) shipment?",
      a: "For COD orders, the exact amount to be collected is displayed on your tracking details page. Pay the associate upon delivery via cash, UPI, or card."
    }
  ];

  return (
    <div className="space-y-12 py-8 px-4 max-w-7xl mx-auto">
      
      {/* 1. Value Proposition Highlights Grid */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
        <div className="bg-white rounded-2xl p-6 shadow-md border border-gray-200/80 hover:shadow-xl transition transform hover:-translate-y-1">
          <div className="w-12 h-12 bg-amber-100 text-amber-600 rounded-xl flex items-center justify-center font-bold mb-4">
            <Zap className="w-6 h-6" />
          </div>
          <h3 className="text-base font-extrabold text-gray-900 mb-1">Express Air Linehaul</h3>
          <p className="text-xs text-gray-600 leading-relaxed">
            Fast nationwide transit powered by Amazon Air cargo aircraft & express linehaul network.
          </p>
        </div>

        <div className="bg-white rounded-2xl p-6 shadow-md border border-gray-200/80 hover:shadow-xl transition transform hover:-translate-y-1">
          <div className="w-12 h-12 bg-emerald-100 text-emerald-600 rounded-xl flex items-center justify-center font-bold mb-4">
            <ShieldCheck className="w-6 h-6" />
          </div>
          <h3 className="text-base font-extrabold text-gray-900 mb-1">Verified OTP Delivery</h3>
          <p className="text-xs text-gray-600 leading-relaxed">
            Secure contactless doorstep delivery verified by 4-digit digital handshake OTP.
          </p>
        </div>

        <div className="bg-white rounded-2xl p-6 shadow-md border border-gray-200/80 hover:shadow-xl transition transform hover:-translate-y-1">
          <div className="w-12 h-12 bg-blue-100 text-blue-600 rounded-xl flex items-center justify-center font-bold mb-4">
            <MapPin className="w-6 h-6" />
          </div>
          <h3 className="text-base font-extrabold text-gray-900 mb-1">Live Hub Checkpoints</h3>
          <p className="text-xs text-gray-600 leading-relaxed">
            Track exact hub scans from origin Fulfillment Center to your local neighborhood station.
          </p>
        </div>

        <div className="bg-white rounded-2xl p-6 shadow-md border border-gray-200/80 hover:shadow-xl transition transform hover:-translate-y-1">
          <div className="w-12 h-12 bg-purple-100 text-purple-600 rounded-xl flex items-center justify-center font-bold mb-4">
            <Headphones className="w-6 h-6" />
          </div>
          <h3 className="text-base font-extrabold text-gray-900 mb-1">24/7 Agent Support</h3>
          <p className="text-xs text-gray-600 leading-relaxed">
            Direct associate contact phone numbers & automated delivery assistance round the clock.
          </p>
        </div>
      </div>

      {/* 2. Amazon Logistics Network Stats Banner */}
      <div className="bg-gradient-to-r from-[#131921] via-[#232F3E] to-slate-900 rounded-3xl p-6 sm:p-10 text-white shadow-2xl relative overflow-hidden">
        <div className="absolute right-0 top-0 w-96 h-96 bg-amber-500/10 rounded-full blur-3xl pointer-events-none" />

        <div className="relative z-10 grid grid-cols-2 md:grid-cols-4 gap-6 text-center sm:divide-x divide-gray-800/80">
          <div className="px-2 sm:px-3">
            <p className="text-2xl sm:text-4xl font-black text-amber-400 font-mono">99.8%</p>
            <p className="text-[11px] sm:text-xs text-gray-300 font-semibold mt-1">On-Time Delivery Rate</p>
          </div>
          <div className="px-2 sm:px-3">
            <p className="text-2xl sm:text-4xl font-black text-white font-mono">1,500+</p>
            <p className="text-[11px] sm:text-xs text-gray-300 font-semibold mt-1">Fulfillment Centers & Hubs</p>
          </div>
          <div className="px-2 sm:px-3">
            <p className="text-2xl sm:text-4xl font-black text-amber-400 font-mono">100M+</p>
            <p className="text-[11px] sm:text-xs text-gray-300 font-semibold mt-1">Packages Tracked & Delivered</p>
          </div>
          <div className="px-2 sm:px-3">
            <p className="text-2xl sm:text-4xl font-black text-white font-mono">24/7</p>
            <p className="text-[11px] sm:text-xs text-gray-300 font-semibold mt-1">Live Database Sync</p>
          </div>
        </div>
      </div>

      {/* 3. How Shipment Tracking Works (4 Step Flow) */}
      <div className="bg-white rounded-3xl p-8 sm:p-10 shadow-lg border border-gray-200">
        <div className="text-center max-w-2xl mx-auto mb-10">
          <span className="bg-amber-100 text-amber-900 font-extrabold text-xs px-3 py-1 rounded-full uppercase tracking-wider">
            Simple & Transparent
          </span>
          <h2 className="text-2xl sm:text-3xl font-black text-gray-900 mt-2">
            How Amazon Shipping Order Journey Works
          </h2>
          <p className="text-xs sm:text-sm text-gray-600 mt-1">
            From merchant packaging to final doorstep handshake, every step is scanned live.
          </p>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6 relative">
          
          {/* Step 1 */}
          <div className="bg-slate-50 p-6 rounded-2xl border border-gray-200 relative">
            <span className="w-8 h-8 rounded-xl bg-[#232F3E] text-amber-400 font-extrabold text-sm flex items-center justify-center mb-4 shadow">
              1
            </span>
            <h4 className="font-extrabold text-sm text-gray-900">Order Creation & Label</h4>
            <p className="text-xs text-gray-600 mt-2 leading-relaxed">
              Admin generates AWB number and thermal shipping label in the warehouse.
            </p>
          </div>

          {/* Step 2 */}
          <div className="bg-slate-50 p-6 rounded-2xl border border-gray-200 relative">
            <span className="w-8 h-8 rounded-xl bg-[#232F3E] text-amber-400 font-extrabold text-sm flex items-center justify-center mb-4 shadow">
              2
            </span>
            <h4 className="font-extrabold text-sm text-gray-900">Sorting Hub Processing</h4>
            <p className="text-xs text-gray-600 mt-2 leading-relaxed">
              Package is scanned at regional air sorting hub and routed to transit linehaul.
            </p>
          </div>

          {/* Step 3 */}
          <div className="bg-slate-50 p-6 rounded-2xl border border-gray-200 relative">
            <span className="w-8 h-8 rounded-xl bg-[#232F3E] text-amber-400 font-extrabold text-sm flex items-center justify-center mb-4 shadow">
              3
            </span>
            <h4 className="font-extrabold text-sm text-gray-900">Out For Delivery</h4>
            <p className="text-xs text-gray-600 mt-2 leading-relaxed">
              Assigned to local delivery associate with live vehicle & phone details.
            </p>
          </div>

          {/* Step 4 */}
          <div className="bg-slate-50 p-6 rounded-2xl border border-gray-200 relative">
            <span className="w-8 h-8 rounded-xl bg-emerald-600 text-white font-extrabold text-sm flex items-center justify-center mb-4 shadow">
              4
            </span>
            <h4 className="font-extrabold text-sm text-gray-900">Safe Handover</h4>
            <p className="text-xs text-gray-600 mt-2 leading-relaxed">
              Delivered safely to customer with OTP handshake & digital signature.
            </p>
          </div>

        </div>
      </div>

      {/* 4. Frequently Asked Questions (FAQ Accordion) */}
      <div className="bg-white rounded-3xl p-8 sm:p-10 shadow-lg border border-gray-200">
        <div className="flex items-center gap-3 mb-6">
          <div className="p-2 bg-amber-500/20 text-amber-800 rounded-xl">
            <HelpCircle className="w-6 h-6" />
          </div>
          <div>
            <h3 className="text-xl font-black text-gray-900">Frequently Asked Questions</h3>
            <p className="text-xs text-gray-500">Everything you need to know about Amazon Shipping tracking</p>
          </div>
        </div>

        <div className="space-y-3">
          {faqs.map((faq, index) => {
            const isOpen = openFaq === index;
            return (
              <div 
                key={index}
                className="border border-gray-200 rounded-2xl overflow-hidden transition"
              >
                <button
                  onClick={() => setOpenFaq(isOpen ? null : index)}
                  className="w-full p-4 text-left font-bold text-sm text-gray-900 bg-slate-50 hover:bg-slate-100 flex justify-between items-center transition"
                >
                  <span>{faq.q}</span>
                  <ChevronDown className={`w-4 h-4 text-gray-500 transition-transform ${isOpen ? 'rotate-180' : ''}`} />
                </button>

                {isOpen && (
                  <div className="p-4 text-xs text-gray-700 bg-white leading-relaxed border-t border-gray-100">
                    {faq.a}
                  </div>
                )}
              </div>
            );
          })}
        </div>
      </div>

    </div>
  );
};
